# 1. Importul bibliotecilor

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 2. Tipuri de date si atribute

## 2.1. Tipuri de date NumPy

In [2]:
# crearea unui array unidimensional
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
# crearea unui array bidimensional
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [4]:
# crearea unui array tridimensional
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

## 2.2. Atributele elementelor de tip array
### 2.2.1. Forma array - `.shape`

In [5]:
# vizualizarea formei lui a1
a1.shape

(3,)

In [6]:
# vizualizarea formei lui a2
a2.shape

(2, 3)

In [7]:
# vizualizarea formei lui a3
a3.shape

(3, 2, 3)

### 2.2.2. Numarul dimensiunii - `.ndim`

In [8]:
# vizualizarea numarului de dimensiuni pentru a1
a1.ndim

1

In [9]:
# vizualizarea numarului de dimensiuni pentru a2
a2.ndim

2

In [10]:
# vizualizarea numarului de dimensiuni pentru a3
a3.ndim

3

### 2.2.3. Tipul elementelor componente - `.dtype`

In [11]:
# determinarea tipului elementelor lui a1
a1.dtype

dtype('int32')

In [12]:
# determinarea tipului elementelor lui a2
a2.dtype

dtype('float64')

In [13]:
# determinarea tipului elementelor lui a3
a3.dtype

dtype('int32')

### 2.2.4. Conversia tipului de date a componentelor - `astype('noul_tip')`

In [14]:
# modificarea tipului elementelor lui a1 din int32 in int8
a1 = a1.astype('int8')
a1.dtype

dtype('int8')

In [15]:
# modificarea tipului elementelor lui a2 din float64 in int32
a2 = a2.astype('int32')
a2.dtype

dtype('int32')

In [16]:
# modificarea tipului elementelor lui a3 din int32 in float32
a3 = a3.astype('float32')
a3.dtype

dtype('float32')

### 2.2.5. Tipul array - `type()`

In [17]:
# determinarea tipului lui a1
type(a1)

numpy.ndarray

In [18]:
# determinarea tipului lui a2
type(a2)

numpy.ndarray

In [19]:
# determinarea tipului lui a3
type(a3)

numpy.ndarray

### 2.2.6. Numarul elementelor componente - `.size`

In [20]:
# determinarea numarului de elemente in a1
a1.size

3

In [21]:
# determinarea numarului de elemente in a2
a2.size

6

In [22]:
# determinarea numarului de elemente in a3
a3.size

18

### 2.2.7. Volumul de memorie ocupat de un element (bytes) - `.itemsize`

In [23]:
# determinarea volumului de memorie coupat de un element al a1
a1.itemsize

1

In [24]:
# determinarea volumului de memorie coupat de un element al a2
a2.itemsize

4

In [25]:
# determinarea volumului de memorie coupat de un element al a3
a3.itemsize

4

### 2.2.8. Volumul de memorie ocupat de un array (bytes) - `.nbytes`

In [26]:
# determinarea volumului de memorie coupat de a1
a1.nbytes

3

In [27]:
# determinarea volumului de memorie coupat de a2
a2.nbytes

24

In [28]:
# determinarea volumului de memorie coupat de a3
a3.nbytes

72

## 2.3. Transformarea unui tip NumPy in tip Pandas

In [29]:
# transformarea unui array unidimensional in serie pandas
s = pd.Series(a1)
s

0    1
1    2
2    3
dtype: int8

In [30]:
# transformarea unui array bidimensional in dataframe
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

# 3. Crearea unui array NumPy
## 3.1. Crearea unui array cu ajutorul listelor

In [31]:
# se creaza 2 liste Python
lt1 = [6, 2, 8, 4]
lt2 = [7, 9, 3, 5]
lt1, lt2

([6, 2, 8, 4], [7, 9, 3, 5])

In [32]:
# se creaza un array unidimensional din lt1
ar1=np.array(lt1)
ar1

array([6, 2, 8, 4])

In [33]:
# se creaza un array bidimensional din lt1 si lt2
ar2=np.array([lt1,lt2])
ar2

array([[6, 2, 8, 4],
       [7, 9, 3, 5]])

In [34]:
# se o copie a ar2
ar3 = ar2.copy()
ar3

array([[6, 2, 8, 4],
       [7, 9, 3, 5]])

## 3.2. Crearea unui array din elemente identice

In [35]:
# se creaza un array doar din elemente 0 de forma (4,3) specificandu-se tipul elementelor
ar4 = np.zeros((4,3), dtype = 'int8')
ar4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [36]:
# se creaza un array doar din elemente 0 de forma array ar2
ar5 = np.zeros_like(ar2)
ar5

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
# se creaza un array doar din elemente 1 de forma (3,5)
ar6 = np.ones((3,5))
ar6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
# se creaza un array doar din elemente 1 de forma array a3 specificandu-se tipul elementelor
ar7 = np.ones_like(a3, dtype = "float16")
ar7

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float16)

In [39]:
# se creaza un array doar din elemente de un singura valoarea (ex. 5) de forma (3,3) specificandu-se tipul elementelor
ar8 = np.full((3,3), 5, dtype = "int16")
ar8

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int16)

In [40]:
# se creaza un array doar din elemente de un singura valoarea (ex. 10) de forma array a2
ar9 = np.full_like(a2, 10)
ar9

array([[10, 10, 10],
       [10, 10, 10]])

In [41]:
# se creaza un array unitar de forma (5,5) (ce va avea 1 pe diagonala principala si 0 in rest)
ar10 = np.identity(5)
ar10

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 3.3. Crearea unui array 1D cu elemente dintr-un interval

In [42]:
# se creaza un array unidimensional cu elementele intregi de la 0 la 9
ar11 =  np.arange(10)
ar11

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# se creaza un array unidimensional cu elementele intregi de la 5 la 9
ar12 =  np.arange(3, 10)
ar12

array([3, 4, 5, 6, 7, 8, 9])

In [44]:
# se creaza un array unidimensional cu elementele intregi de la 4 la 9 luate cu pasul 2
ar13 =  np.arange(4, 10, 2)
ar13

array([4, 6, 8])

In [45]:
# se creaza un array ce repeta de 3 ori elementele ar13
ar14 = np.repeat(ar12, 3)
ar14

array([5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9])

In [46]:
# se creaza un array format din 20 de elemente situate uniform in intervalul 0 - 10
arr15 = np.linspace(0, 10, 20)
arr15

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## 3.4. Crearea unui array cu elemente aliatoare

In [110]:
# se creaza un array bidimensional de forma (3,5) cu elementele random intregi de la 2 la 9
ar16 =  np.random.randint(2, 10, size=(3,5))
ar16

array([[4, 8, 3, 9, 5],
       [5, 9, 8, 7, 7],
       [8, 7, 4, 5, 8]])

In [48]:
# se creaza un array bidimensional de forma (3,4) cu elementele random float de la 0 la 0,999...
ar17 =  np.random.random((3,4))
ar17

array([[0.74921273, 0.74272149, 0.57056437, 0.96509886],
       [0.51091355, 0.7024006 , 0.35777334, 0.28845526],
       [0.8763362 , 0.05839317, 0.50071185, 0.93594685]])

In [49]:
# se creaza un array 3-dimensional de forma (2,4,5) cu elementele random float de la 0 la 0,999...
ar18 =  np.random.rand(2, 4, 5)
ar18

array([[[0.16818552, 0.2316913 , 0.36586696, 0.68265687, 0.45482735],
        [0.38920201, 0.14659268, 0.73068382, 0.20423392, 0.6991965 ],
        [0.05082447, 0.8221006 , 0.90341912, 0.11541429, 0.50423826],
        [0.68590812, 0.62702417, 0.62077227, 0.09928109, 0.22474293]],

       [[0.0143001 , 0.63937623, 0.36798107, 0.04578308, 0.22903712],
        [0.21340432, 0.64242246, 0.08026327, 0.95635528, 0.04227462],
        [0.21302933, 0.54007422, 0.41349857, 0.8765023 , 0.63793643],
        [0.5894611 , 0.59057744, 0.19907142, 0.52933185, 0.87140561]]])

In [50]:
# se creaza un array de forma ar8 cu elementele random float de la 0 la 0,999...
ar19 =  np.random.random_sample(ar8.shape)
ar19

array([[0.97721646, 0.69262032, 0.51913335],
       [0.7491463 , 0.16166831, 0.77310398],
       [0.50815473, 0.09182504, 0.60262167]])

## 3.5. Setarea elementelor pseudo-random

In [51]:
# se creaza un array cu elementele random
ar20=np.random.random((4,5))
ar20

array([[0.95085377, 0.09098846, 0.57344522, 0.00855359, 0.23744696],
       [0.30314367, 0.9574316 , 0.77603457, 0.07261542, 0.17968631],
       [0.93325042, 0.31198257, 0.00631475, 0.13445846, 0.88260554],
       [0.11603073, 0.64097661, 0.13018846, 0.30453147, 0.58152987]])

In [52]:
# se repeta procedura de creare a aceluiasi array
ar20=np.random.random((4,5))
ar20

array([[0.59340248, 0.4265276 , 0.51073924, 0.17893934, 0.02468251],
       [0.37171015, 0.53367749, 0.69390829, 0.0094128 , 0.94457693],
       [0.74726957, 0.63899382, 0.55984019, 0.65375272, 0.43829182],
       [0.26402314, 0.33572291, 0.55082449, 0.62957102, 0.61507524]])

In [53]:
# seteaza numerele random sa fie pseudo-random si se repeta procedura
np.random.seed(42)
ar20=np.random.random((4,5))
ar20

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [54]:
# se repeta procedura de creare a aceluiasi array cu pseudo-random
np.random.seed(42)
ar20=np.random.random((4,5))
ar20

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

# 4. Vizualizarea elementelor in array
## 4.1. Vizualizarea elementelor unice in array

In [111]:
# se vizualizeaza ar16
ar16

array([[4, 8, 3, 9, 5],
       [5, 9, 8, 7, 7],
       [8, 7, 4, 5, 8]])

In [112]:
# determinarea elementelor unice in ar16
np.unique(ar16)

array([3, 4, 5, 7, 8, 9])

## 4.2. Selectarea elementelor unui array conform indicelui

In [70]:
# vizualizare array unidimensional ar12
ar12

array([3, 4, 5, 6, 7, 8, 9])

In [71]:
# selectarea elementului de pe pozitia 5 a ar11
ar12[4]

7

In [113]:
# vizualizare array bidimensional ar16
ar16

array([[4, 8, 3, 9, 5],
       [5, 9, 8, 7, 7],
       [8, 7, 4, 5, 8]])

In [114]:
# selectarea elementelor liniei a 2
ar16[1]

array([5, 9, 8, 7, 7])

In [115]:
# selectarea elementului de pe linia a 2 poztia 4
ar16[1,3]

7

In [63]:
# vizualizare array tridimensional a3
a3

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]], dtype=float32)

In [64]:
# selectarea elementului din tabelul 3 linia a 1 pozitia 2
a3[2,0,1]

14.0

## 4.3. Selectarea elementelor unui array folosind slicing

In [96]:
# vizualizare array unidimensional ar12
ar12

array([3, 4, 5, 6, 7, 8, 9])

In [86]:
# selectarea primelor 4 elemente array 1D ar12
ar12[:4]

array([3, 4, 5, 6])

In [95]:
# selectarea elementelor al 2, 4 si 5 ale lui ar12
ar12[[1,3,4]]

array([4, 6, 7])

In [116]:
# vizualizare array bidimensional ar16
ar16

array([[4, 8, 3, 9, 5],
       [5, 9, 8, 7, 7],
       [8, 7, 4, 5, 8]])

In [117]:
# selectarea tuturor elementelor celei de a 3 linii a lui ar16
ar16[2,:]

array([8, 7, 4, 5, 8])

In [118]:
# selectarea tuturor elementelor celei de a 4 coloane a lui ar16
ar16[:, 3]

array([9, 7, 5])

In [119]:
# selectarea elementelor 2-4 din ce dea 2 linie lui ar16
ar16[1, 1:4]

array([9, 8, 7])

In [120]:
# selectarea elementelor 1 si 2 din ce dea 2 coloana lui ar16
ar16[0:2, 1]

array([8, 9])

In [121]:
# selectarea elementelor 2-4 din primele 2 linie al lui ar16
ar16[0:2,1:4]

array([[8, 3, 9],
       [9, 8, 7]])

In [122]:
# selectarea elementelor 4 din linia 1, 3 din linia 2 si 5 din linia 3 ale lui ar16
ar16[[0,1,2],[3,2,4]]

array([9, 8, 8])

In [99]:
# vizualizare array tridimensional a3
a3

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]], dtype=float32)

In [98]:
# selectarea primelor 2 elemente din primele linii al primelor 2 tabele din a3
a3[:2,:1,:2]

array([[[1., 2.]],

       [[7., 8.]]], dtype=float32)

# 5. Actualizarea valorilor in array

In [123]:
# vizualizare array bidimensional ar16
ar16

array([[4, 8, 3, 9, 5],
       [5, 9, 8, 7, 7],
       [8, 7, 4, 5, 8]])

In [124]:
# modificara valorii elementului al 3 din linia 2 in 5 ale ar16
ar16[1,2] =5
ar16

array([[4, 8, 3, 9, 5],
       [5, 9, 5, 7, 7],
       [8, 7, 4, 5, 8]])

In [125]:
# modificara valorii elementelelor al 2-4 din linia 1 a ar16 in 7, 4 si 0
ar16[0,1:4] =[7,4,0]
ar16

array([[4, 7, 4, 0, 5],
       [5, 9, 5, 7, 7],
       [8, 7, 4, 5, 8]])

In [127]:
# modificara valorii elementelelor 2 din linile 2 si 3 a ar16 in 2 si 3
ar16[1:3,1] =[2,3]
ar16

array([[4, 7, 4, 0, 5],
       [5, 2, 5, 7, 7],
       [8, 3, 4, 5, 8]])

In [128]:
# creara unei liste bidimensionale (2,2)
l = [[4, 1], [0, 4]]
l

[[4, 1], [0, 4]]

In [129]:
# modificara valorii elementelor 3, 4 din liniile 2 si 3 ale ar16 ci valorile listei
ar16[1:3,2:4] =l
ar16

array([[4, 7, 4, 0, 5],
       [5, 2, 4, 1, 7],
       [8, 3, 0, 4, 8]])

In [130]:
# modificarea valorilor tuturor elementelor liniei 2 in 9
ar16[1, :] = 9
ar16

array([[4, 7, 4, 0, 5],
       [9, 9, 9, 9, 9],
       [8, 3, 0, 4, 8]])

In [132]:
# modificarea valorilor tuturor elementelor coloanei 5 in 2
ar16[:, 4] = 2
ar16

array([[4, 7, 4, 0, 2],
       [9, 9, 9, 9, 2],
       [8, 3, 0, 4, 2]])

# 6. Operatii aritmetice "element cu element" in array

In [139]:
# vizualizare array bidimensional ar16
ar16

array([[4, 7, 4, 0, 2],
       [9, 9, 9, 9, 2],
       [8, 3, 0, 4, 2]])

In [158]:
# Sumarea elementelor lui ar16 cu 2
arps = ar16 + 2
arps

array([[ 6,  9,  6,  2,  4],
       [11, 11, 11, 11,  4],
       [10,  5,  2,  6,  4]])

In [159]:
# Sumarea 5 din elementelor lui ar16
arms = ar16 -5
arms

array([[-1,  2, -1, -5, -3],
       [ 4,  4,  4,  4, -3],
       [ 3, -2, -5, -1, -3]])

In [160]:
# }multirea elementelor lui ar16 cu 3
aris = ar16 * 3
aris

array([[12, 21, 12,  0,  6],
       [27, 27, 27, 27,  6],
       [24,  9,  0, 12,  6]])

In [140]:
# se creaza unui alt array de aceeasi forma ca ar16
ar21 =  np.random.randint(0, 10, size=(ar16.shape))
ar21

array([[8, 6, 1, 3, 8],
       [1, 9, 8, 9, 4],
       [1, 3, 6, 7, 2]])

In [141]:
# Sumarea ar16 si ar21 si formarea ar22
ar22 = ar16 + ar21
ar22

array([[12, 13,  5,  3, 10],
       [10, 18, 17, 18,  6],
       [ 9,  6,  6, 11,  4]])

In [142]:
# Sumarea ar16 si ar21 folosind functia np.add()
ar22 = np.add(ar16, ar21)
ar22

array([[12, 13,  5,  3, 10],
       [10, 18, 17, 18,  6],
       [ 9,  6,  6, 11,  4]])

In [143]:
# Sumarea lui ar16 din ar21 si formarea ar23
ar23 = ar21 - ar16
ar23

array([[ 4, -1, -3,  3,  6],
       [-8,  0, -1,  0,  2],
       [-7,  0,  6,  3,  0]])

In [144]:
# Inmultirea ar16 si ar21 si formarea ar24
ar24 = ar16 * ar21
ar24

array([[32, 42,  4,  0, 16],
       [ 9, 81, 72, 81,  8],
       [ 8,  9,  0, 28,  4]])

In [145]:
# Impartirea lui ar16 la ar21 si formarea ar25
ar25 = ar16 / ar21
ar25

array([[0.5       , 1.16666667, 4.        , 0.        , 0.25      ],
       [9.        , 1.        , 1.125     , 1.        , 0.5       ],
       [8.        , 1.        , 0.        , 0.57142857, 1.        ]])

In [146]:
# Impartirea cu rotungire a lui ar16 la ar21 si formarea ar26
ar26 = ar16 // ar21
ar26

array([[0, 1, 4, 0, 0],
       [9, 1, 1, 1, 0],
       [8, 1, 0, 0, 1]], dtype=int32)

In [148]:
# Ridicarea lui ar21 la patrat
ar26 = ar21 **2
ar26

array([[64, 36,  1,  9, 64],
       [ 1, 81, 64, 81, 16],
       [ 1,  9, 36, 49,  4]], dtype=int32)

In [150]:
# Ridicarea lui ar21 la patrat utilizand functia np.square()
ar26=np.square(ar21)
ar26

array([[64, 36,  1,  9, 64],
       [ 1, 81, 64, 81, 16],
       [ 1,  9, 36, 49,  4]], dtype=int32)

In [154]:
# Determinarea restului divizarii elemetelor lui ar21 la 3
ar27 = ar21 % 3
ar27

array([[2, 0, 1, 0, 2],
       [1, 0, 2, 0, 1],
       [1, 0, 0, 1, 2]], dtype=int32)

In [155]:
# Determinarea exponentei elementelor lui ar 21
ar28 = np.exp(ar21)
ar28

array([[2.98095799e+03, 4.03428793e+02, 2.71828183e+00, 2.00855369e+01,
        2.98095799e+03],
       [2.71828183e+00, 8.10308393e+03, 2.98095799e+03, 8.10308393e+03,
        5.45981500e+01],
       [2.71828183e+00, 2.00855369e+01, 4.03428793e+02, 1.09663316e+03,
        7.38905610e+00]])

In [156]:
# Determinarea logaritmului natural al elementelor lui ar28
ar29 = np.log(ar28)
ar29

array([[8., 6., 1., 3., 8.],
       [1., 9., 8., 9., 4.],
       [1., 3., 6., 7., 2.]])

In [157]:
# Determinarea sinusului elementelor lui ar29
ar30 = np.sin(ar29)
ar30

array([[ 0.98935825, -0.2794155 ,  0.84147098,  0.14112001,  0.98935825],
       [ 0.84147098,  0.41211849,  0.98935825,  0.41211849, -0.7568025 ],
       [ 0.84147098,  0.14112001, -0.2794155 ,  0.6569866 ,  0.90929743]])

# 7. Operatii de agregare a elementelor unui array

In [164]:
# vizualizare array unidimensional ar12
ar12

array([3, 4, 5, 6, 7, 8, 9])

In [165]:
# Determinarea sumei tuturor elemtelor cu functia sum() din python
sum(ar12)

42

In [166]:
# Determinarea sumei tuturor elemtelor cu functia sum() din numpy
np.sum(ar12)

42

- diferenta de timp dintre execurarea operatiilor cu `sum()` si `np.sum()`

In [171]:
# crearea unui array imens
arr_imens = np.random.random(100000)

# vizualizarea numarului de elemnte in arr_imens
print(f'Numarul de elemete: {arr_imens.size}')

# vizualizarea primelor 5 elemente
print(f'Primele 5 elemente: {arr_imens[:5]}')

# determinarea timpului de executie a operatiei sum() din python cu functia magica %timeit
print('Timpul de executie a operatie de sumare a tutror elementelor cu:')
print(' - functia sum() din Python')
%timeit sum(arr_imens)

# determinarea timpului de executie a operatiei np.sum() din numpy cu functia magica %timeit
print(' - functia np.sum() din NumPy')
%timeit np.sum(arr_imens)

Numarul de elemete: 100000
Primele 5 elemente: [0.01005622 0.7266825  0.78176096 0.87737011 0.49983115]
Timpul de executie a operatie de sumare a tutror elementelor cu:
 - functia sum() din Python
5.66 ms ± 144 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
 - functia np.sum() din NumPy
31.2 µs ± 176 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [172]:
# determinarea raportului dintre timpul de executie a opertiilor python si numpy
(5.66*10**(-3))/(31.2*10**(-6))

181.4102564102564

In [173]:
# vizualizare array bidimensional ar21
ar21

array([[8, 6, 1, 3, 8],
       [1, 9, 8, 9, 4],
       [1, 3, 6, 7, 2]])

In [174]:
# Determinarea valorii medii a elementelor pe linii in ar21
np.mean(ar21, axis=1)

array([5.2, 6.2, 3.8])

In [175]:
# Determinarea valorii medii a elementelor pe coloane in ar21
np.mean(ar21, axis=0)

array([3.33333333, 6.        , 5.        , 6.33333333, 4.66666667])

In [176]:
# Determinarea valorii medii a tuturor elementelor ar21
np.mean(ar21)

5.066666666666666

In [177]:
# Determinarea valorii minime a tuturor elementelor ar21
np.min(ar21)

1

In [179]:
# Determinarea valorii maxime a tuturor elementelor ar21
np.max(ar21)

9

In [180]:
# Determinarea valorii abaterii medii standarte a tuturor elementelor ar21
np.std(ar21)

2.9544693074880453

In [181]:
# Determinarea valorii abaterii medii patratice a tuturor elementelor ar21
np.var(ar21)

8.72888888888889

In [193]:
# crearae unui array bidimensional patratic (5,5)
ar31 =  np.random.randint(0, 10, size=(5,5))
ar31

array([[1, 3, 3, 8, 2],
       [6, 5, 6, 2, 3],
       [5, 9, 4, 3, 2],
       [9, 0, 5, 3, 4],
       [7, 5, 9, 4, 9]])

In [194]:
# Determinara determinantului matricii corespunzataore lui ar31
np.linalg.det(ar31)

5935.000000000002

# 8. Modificare formei unui array
Cand se realizaza operatii cu doua variabile de tip array, NumPy compara formele acestora, iar pentru aceasta trebuie sa se respecte una din cele 2 reguli
* formele trebuie sa fie identice
* o dimensiune trebuie sa fie 1

In [189]:
# vizualizarea lui a2
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [190]:
# vizualizarea formei lui a2
a2.shape

(2, 3)

In [191]:
# vizualizarea numarului dimensiunii lui a2
a2.ndim

2

In [185]:
# vizualizarea lui a3
a3

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]], dtype=float32)

In [186]:
# vizualizarea formei lui a3
a3.shape

(3, 2, 3)

In [187]:
# vizualizarea numarului dimensiunii lui a3
a3.ndim

3

Daca se incerca imultirea a2*a3 se obtine o eroare deoarece formele nu respecta nici una din cele 2 reguli

In [195]:
# formarea unui array 1D din a2 prin alipirea tuturor liniilor
a4 = a2.ravel()
a4

array([1, 2, 3, 4, 5, 6])

In [196]:
# modificarea formei lui a2 prin adaugarea inca a unei dimensiuni
a4 = a2.reshape(1,2,3)
a4

array([[[1, 2, 3],
        [4, 5, 6]]])

In [199]:
# vizualizarea formei lui a4
a4.shape

(1, 2, 3)

In [197]:
# vizualizarea numarului dimensiunii lui a4
a4.ndim

3

In [198]:
# se realizeaza operatia de imultirea a2*a3
a2*a3

array([[[  1.,   4.,   9.],
        [ 16.,  25.,  36.]],

       [[  7.,  16.,  27.],
        [ 40.,  55.,  72.]],

       [[ 13.,  28.,  45.],
        [ 64.,  85., 108.]]])

In [200]:
# stergerea tuturor dimensiunilor unitare
a5 = a4.squeeze()
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [201]:
# vizualizarea formei lui a5
a5.shape

(2, 3)

# 9. Transpusa  unui array

In [204]:
# vizualizarea lui ar21
ar21

array([[8, 6, 1, 3, 8],
       [1, 9, 8, 9, 4],
       [1, 3, 6, 7, 2]])

In [205]:
# vizualizarea formei lui ar21
ar21.shape

(3, 5)

In [206]:
# vizualizarea numarului dimensiunii lui ar21
ar21.ndim

2

In [207]:
# obtinerea transpusei lui ar21
a6 = ar21.T
a6

array([[8, 1, 1],
       [6, 9, 3],
       [1, 8, 6],
       [3, 9, 7],
       [8, 4, 2]])

In [209]:
# vizualizarea formei lui a76
a6.shape

(5, 3)

In [210]:
# vizualizarea numarului dimensiunii lui a6
a6.ndim

2

# 10. Îmulțirea a 2 matrici corespunzatoare array 

In [211]:
# se creaza 2 matrice de aceleasi dimensiuni
np.random.seed(9)

mat1=np.random.randint(10, size=(3,4))
mat2=np.random.randint(10, size=(3,4))

In [212]:
# vizualizarea lui mat1
mat1

array([[5, 6, 8, 6],
       [1, 6, 4, 8],
       [1, 8, 5, 1]])

In [213]:
# vizualizarea lui mat2
mat2

array([[0, 8, 8, 8],
       [2, 6, 8, 1],
       [8, 3, 5, 3]])

In [214]:
# vizualizarea formelor lui mat1 si mat2
mat1.shape, mat2.shape

((3, 4), (3, 4))

In [215]:
# imultirea "element cu element" a mat1 si mat2 (Hadamard product)
mat1 * mat2

array([[ 0, 48, 64, 48],
       [ 2, 36, 32,  8],
       [ 8, 24, 25,  3]])

Pentru îmultimrea a doua matrici matrici de formele (m,n) si (x,y) se realizarea operatia `DOT product` care necesită ca n=x iar matricea rezultanta va avea forma (m,y).
Mai multe se pot gasi pe adresele:
https://www.mathsisfun.com/algebra/matrix-multiplying.html

http://matrixmultiplication.xyz/

Inmultirea dot a matricilor mat1 si mat2 va rezulta in eroare deoarece ambele au forma (3,4)
Pentru a exclude eroare se schimba forma unei dintre matrici prin intermediul transpusei

In [216]:
# determinarea transpusei lui mat2
mat2_T = mat2.T
mat2_T

array([[0, 2, 8],
       [8, 6, 3],
       [8, 8, 5],
       [8, 1, 3]])

In [217]:
# realizarea operatiei dot product dintre mat1 si mat2_T
mat3 = np.dot(mat1, mat2_T)
mat3

array([[160, 116, 116],
       [144,  78,  70],
       [112,  91,  60]])

In [218]:
# vizualizarea formei lui mat3
mat3.shape

(3, 3)

In [219]:
# realizarea operatiei dot product dintre mat2_T si mat1
mat4 = np.dot(mat2_T, mat1)
mat4

array([[ 10,  76,  48,  24],
       [ 49, 108, 103,  99],
       [ 53, 136, 121, 117],
       [ 44,  78,  83,  59]])

In [220]:
# vizualizarea formei lui mat4
mat4.shape

(4, 4)